### ISSUE TITLE
release version 0.2

### ISSUE THREAD

**Issue by r41d** [anyc/skiller-ctl#1]
First off: awesome little tool :)
I saw that the tool had some improvements after May 12, 2016. Today I created an [ebuild for skiller-ctl](https://github.com/SuperTux88/gentoo-overlay/tree/master/sys-apps/skiller-ctl) and would like to install version 0.2 instead of 9999 from git :)

Cheers

**Comment by r41d** [comment]
Had I only looked a bit further and searched until I found your overlay.
Glad to see that you're a Gentoo user too =)

**Comment by anyc** [comment]
Hi, thanks! I just tagged the last commit from May and bumped my ebuild, too.
